### PR TITLE
Implementation of Explore Stories page is completed

### PR DESCRIPTION
**Pull request by TevfikOzbilgin**
Story Exploration page now has some bug fixes as well as some improvements in the code. It now works with true values within the scope, and input forms are in better look with the Google Map aligned with them.

### CODE REVIEW

**Comment by enshkn** [comment]
Hello Tevfik, a total of 26 thousand lines have been added with 7 commits, there is probably an error or confusion, also 66 files have changed, this shows that the entire frontend structure has changed, so many changes have naturally led to conflict. This makes code review impossible. In order to be able to analyse and test the changes, we need to limit the developments to only the files that have been developed, so you need to create a new branch from dev-react and make your developments by changing only the relevant files. This way we can test the developments to review the views after release.

**Comment by mucahitugur** [comment]
also I think we should not change main things now because we will show our app at 4 th January. We are writing report right now. Major change can cause disaster.

**Comment by hdenizdogan** [comment]
Hello, this seems like a major update on all pages, components, dependencies etc. At this stage of the project we should focus on writing our reports and at worst-case, fixing bugs instead of adding new features.

**Comment by hdenizdogan** [comment]
PR closed without merging due to reasons explained above.

**Pull request closed without merging**
