### PR TITLE
584 storydetail page update on webapp

### PR DESCRIPTION
**Pull request by gokalpayaz**
closing #584 

1. I have updated storylist page.
2. Updated timeline and search to have better real estate
3. Added links to story cards
4. Many little visual tweaks

### CODE REVIEW

**Comment by gorkemkuyucu** [comment]
@hdenizdogan also requested comments to show createdAt date. It will be added in this PR.

**Review by hdenizdogan — APPROVED** [review]
Checked it locally. OK.

**Comment by gorkemkuyucu** [comment]
We cannot click on the labels to use label search now. We need to fix this problem before merging.

**Comment by gorkemkuyucu** [comment]
We also need to update the qr with the latest .apk release. I will send this commit to this brach since this one will be one of the last PR before delivery.

**Review by gorkemkuyucu — APPROVED** [review]
Tested locally and everthing is working fine. Added some commits related to tag search and UI fixes. All the things seems on order.

**Comment by gorkemkuyucu** [comment]
Button UI change caused a conflict. I solved it on the merge editor. I'm merging the pull request with reviews and little additions i mentioned above.

**Pull request merged**
